import { setupWorker } from 'msw/browser'
import { handlers } from './handlers'

/**
 * The MSW worker for the browser (dev). Started from `main.tsx` only when `VITE_ENABLE_MSW=true`
 * (wired in T012), so a normal `yarn dev` still talks to the real api via the Vite proxy. Requires
 * `public/mockServiceWorker.js` (generated by `yarn msw init public`).
 */
export const worker = setupWorker(...handlers)
